### ISSUE TITLE
Error for Craftbukkit R6 (MC: 1.2.2 )

### ISSUE THREAD

**Issue by XxCoolGamesxX** [yetanotherx/ModTRS#45]
What steps will reproduce the problem?
1. Start the server.

What version of the product are you using?
ModTRS v2.1

Do you have an error log of what happened?

Error occurred while enabling ModTRS v2.1 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/util/config/Configuration
    at yetanotherx.bukkitplugin.ModTRS.util.MessageHandler.load(MessageHandler.java:27)
    at yetanotherx.bukkitplugin.ModTRS.ModTRS.onEnable(ModTRS.java:79)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:363)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:250)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:232)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:369)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:356)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:187)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:420)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)
Caused by: java.lang.ClassNotFoundException: org.bukkit.util.config.Configuration
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:41)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 12 more

Please provide any additional information below.

I tested ModTRS v2.1 with Craftbukkit R6 (MC: 1.2.2 ) and it will break.

**Comment by ghost** [comment]
The reason for these errors is that ModTRS is using the old configuration methods. Yetanotherx has accepted a pull request, but has not built it, or has but hasn't uploaded it. I suggest compiling it yourself... :)
